apiVersion: apps/v1
kind: Deployment
metadata:
  name: javapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javapp
  template:
    metadata:
      labels:
        app: javapp
    spec:
      containers:
        - name: javapp
          image: haneeshdevops/springbootecommerceapplication_app:latest
          env:
            - name: DB_HOST
              value: postgresql
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8084
